# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Run Appium Tests
        run: mvn clean test -Pandroid -Dmaven.test.failure.ignore=true

      - name: Publish Test Report
        uses: starburstdata/action-testng-report@v1.0.2
        with:
            check_name: TestNG
            github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Test Report2
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: TestReporter            # Name of the check run which will be created
          path: target/surefire-reports/junitreports/*.xml    # Path to test results
          reporter: java-junit       # Format of test results



